services:
  - type: web
    name: celebrity-browser-backend
    runtime: node
    plan: starter
    buildCommand: "cd backend && npm install"
    startCommand: "cd backend && npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DB_URL
        scope: env
      - key: JWT_SECRET
        scope: env
      - key: STRIPE_SECRET_KEY
        scope: env
      - key: STRIPE_PUBLIC_KEY
        scope: env
      - key: CORS_ORIGIN
        value: https://celebrity-browser-frontend.onrender.com,https://staraccess.vercel.app,https://celebritybrowser.vercel.app,http://localhost:3000,http://localhost:5173

  - type: static
    name: celebrity-browser-frontend
    staticPublishPath: ./frontend/dist
    buildCommand: "cd frontend && npm install && npm run build"
    envVars:
      - key: VITE_API_URL
        value: https://celeb-backend-gy6s.onrender.com/api
